# Generated by Django 5.2.4 on 2025-08-01 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_time')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_name', models.CharField(max_length=255, verbose_name='存储文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_url', models.URLField(verbose_name='文件访问URL')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('category', models.CharField(choices=[('image', '图片'), ('document', '文档'), ('video', '视频'), ('audio', '音频'), ('other', '其他')], default='other', max_length=20, verbose_name='文件分类')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='图片宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='图片高度')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='音视频时长')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('related_model', models.CharField(blank=True, max_length=100, verbose_name='关联模型')),
                ('related_id', models.CharField(blank=True, max_length=100, verbose_name='关联ID')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_time')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('action', models.CharField(choices=[('view', '查看'), ('download', '下载')], max_length=20, verbose_name='操作类型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='访问用户')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='file_manager.uploadedfile')),
            ],
            options={
                'verbose_name': '文件访问日志',
                'verbose_name_plural': '文件访问日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['uploaded_by', 'category'], name='file_manage_uploade_804bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['file_type'], name='file_manage_file_ty_ea1142_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['is_public'], name='file_manage_is_publ_bc5c9a_idx'),
        ),
    ]
