# Generated by Django 5.2.4 on 2025-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_url',
            field=models.URLField(max_length=1000, verbose_name='文件访问URL'),
        ),
    ]
