# Generated by Django 5.2.4 on 2025-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_alter_uploadedfile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='related_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关联ID'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='related_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='关联模型'),
        ),
    ]
