# Generated by Django 5.2.4 on 2025-07-23 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_time')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_time')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#cccccc', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_time')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_time')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('REVIEW', '审核中'), ('PUBLISHED', '已发布')], default='DRAFT', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='articles', to='article.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
